language: php

php:
    - '7.1'
    - '7.2'

install:
    - composer install --no-interaction
    - composer info

before_script:
    - composer global require kherge/box
    - export PATH=$PATH:$HOME/.composer/vendor/bin/

script:
    - phpunit
    - composer install --no-interaction --no-dev
    - box build -v

notifications:
    email: true
