language: php

php:
    - '7.1'
    - '7.2'

install:
    - composer install --no-interaction
    - composer info

before_script: composer global require kherge/box

script:
    - phpunit
    - composer install --no-interaction --no-dev
    - ~/.composer/bin/box build -v

notifications:
    email: true
