language: php

php:
    - '7.1'
    - '7.2'

install:
    - composer install --no-interaction
    - composer info

before_script:
    - composer global require kherge/box
    - export PATH=$PATH:$HOME/.composer/vendor/bin/

script:
    - phpunit
    - composer install --no-interaction --no-dev
    - box build -v
    - sha1sum build/myapp.phar > build/myapp.phar.version
    - rm build/.gitignore

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
        branch: master
    local-dir: build

notifications:
    email: true
