language: php

php:
    - '7.1'
    - '7.2'

install:
    - composer install --no-interaction
    - composer info

script:
    - phpunit
    - composer install --no-interaction --no-dev
    - box build -v

notifications:
    email: true
